# Generated by Django 5.0.2 on 2024-05-17 16:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("followers", "0003_alter_follower_from_user_alter_follower_to_user"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="followers",
            field=models.ManyToManyField(
                help_text="User followers",
                through="followers.Follower",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="cover",
            field=models.ImageField(
                blank=True,
                help_text="User cover",
                null=True,
                upload_to="blog/images/covers/",
            ),
        ),
    ]
