# Generated by Django 5.0.6 on 2024-07-21 17:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0007_article_extras_article_headline"),
        ("reports", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="reports",
            field=models.ManyToManyField(
                help_text="Article reports",
                related_name="reports",
                through="reports.Report",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
