# Generated by Django 5.0.2 on 2024-05-16 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('👍🏻', '👍🏻'), ('❤️', '❤️'), ('🤣', '🤣'), ('😲', '😲'), ('🤔', '🤔'), ('😡', '😡')], help_text='Reaction', max_length=8)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date reacted')),
                ('article', models.ForeignKey(help_text='Article', on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
            ],
        ),
    ]
