# Generated by Django 5.0.2 on 2024-05-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reactions", "0003_alter_reaction_value"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reaction",
            name="value",
        ),
        migrations.AddField(
            model_name="reaction",
            name="emoji",
            field=models.CharField(
                choices=[
                    ("👍🏻", "👍🏻 Like"),
                    ("❤️", "❤️ Love"),
                    ("🤣", "🤣 Funny"),
                    ("😲", "😲 Wow"),
                    ("🤔", "🤔 Thinking"),
                    ("😡", "😡 Angry"),
                ],
                default="👍🏻",
                help_text="Reaction",
                max_length=8,
            ),
        ),
    ]
