# Generated by Django 5.0.6 on 2024-06-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0004_rename_text_comment_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="extras",
            field=models.JSONField(
                blank=True,
                help_text="Comment extra data like summary etc...",
                null=True,
            ),
        ),
    ]
