# Generated by Django 5.0.2 on 2024-05-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reactions", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reaction",
            name="value",
            field=models.CharField(
                choices=[
                    ("👍🏻", "👍🏻"),
                    ("❤️", "❤️"),
                    ("🤣", "🤣"),
                    ("😲", "😲"),
                    ("🤔", "🤔"),
                    ("😡", "😡"),
                ],
                default="👍🏻",
                help_text="Reaction",
                max_length=8,
            ),
        ),
    ]
