# Generated by Django 5.0.2 on 2024-05-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(
                db_index=True, help_text="Tag Name", max_length=32, unique=True
            ),
        ),
    ]
