# Generated by Django 5.0.7 on 2024-08-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0002_alter_tag_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="description",
            field=models.CharField(
                db_index=True, help_text="Tag Description", max_length=256
            ),
        ),
    ]
