# Generated by Django 5.0.2 on 2024-05-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Topic Name', max_length=32, unique=True)),
                ('color', models.CharField(db_index=True, help_text='Tag color', max_length=8, unique=True)),
                ('description', models.CharField(db_index=True, help_text='Topic Description', max_length=256)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date created')),
            ],
        ),
    ]
