# Generated by Django 5.0.6 on 2024-07-21 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("articles", "0007_article_extras_article_headline"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message",
                    models.CharField(
                        db_index=True,
                        help_text="Message that will help us understand and handle the situation",
                        max_length=256,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("rude", "Rude or vulgar"),
                            ("harassment", "Harassment or hate speech"),
                            ("spam", "Spam"),
                            ("copy", "Copy right issue"),
                            ("inappropriate", "Inappropriate"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        help_text="Report reason",
                        max_length=256,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Last update"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Date published"),
                ),
                (
                    "article",
                    models.ForeignKey(
                        help_text="Reported Article",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="articles.article",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Reporter",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
