# Generated by Django 5.0.6 on 2024-07-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="is_approved",
            field=models.BooleanField(
                default=False, help_text="Designates if the abuse report is correct"
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="reason",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Rude or vulgar"),
                    (1, "Harassment or hate speech"),
                    (2, "Spam"),
                    (3, "Copy right issue"),
                    (4, "Inappropriate"),
                    (5, "Other"),
                ],
                db_index=True,
                default=0,
                help_text="Report reason",
            ),
        ),
    ]
