# Generated by Django 5.0.2 on 2024-05-17 16:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_initial"),
        ("comments", "0002_initial"),
        ("reactions", "0003_alter_reaction_value"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="comments",
            field=models.ManyToManyField(
                help_text="Article comments",
                related_name="comments",
                through="comments.Comment",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="reactions",
            field=models.ManyToManyField(
                help_text="Article reactions",
                related_name="reactions",
                through="reactions.Reaction",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
