# Generated by Django 5.0.2 on 2024-05-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_article_comments_article_reactions"),
        ("tags", "0002_alter_tag_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Article tags",
                related_name="articles",
                to="tags.tag",
            ),
        ),
    ]
