# Generated by Django 5.0.2 on 2024-05-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0005_article_stargazers"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="recommendations",
            field=models.ManyToManyField(
                help_text="Similar articles", to="articles.article"
            ),
        ),
    ]
