# Generated by Django 5.0.7 on 2024-08-17 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0008_article_reports"),
        ("categories", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="category",
            field=models.ForeignKey(
                default=1,
                help_text="Article category",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="articles",
                to="categories.category",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="article",
            name="user",
            field=models.ForeignKey(
                help_text="Article owner",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="articles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
